name: challenge1
on: workflow_dispatch


jobs:
    job1:
         name: job1
         runs-on: ubuntu-latest
         steps:
         - name: today's date
           run: $(date +'%Y-%m-%d')

         - name: Working Directory
           run: pwd

         - name: Contents of directory:
           run: ls -al
    
    job2:
         name: job2
         runs-on: ubuntu-latest
         steps:
         - name: setup python
           uses: actions/setup-python@v4
           with:
             python-version: 3.10

         - name: check version of python
           run: python --version

         - name: setup pandas
           run: pip install pandas

         - name: Create file artifact.py
           run: echo "# This is my python artifact" > artifact.py

         - name: Run artifact
           run: python artifact.py
