name: tutorial1
on: push

jobs:
    job1:
         name: job1
         runs-on: ubuntu-latest
         steps:
         - name: step1
           run: echo "Hello from job1"
         - name: Echo today's date
           run: echo "Today's date is $(date +'%Y-%m-%d')"

    job2:
         name: job2
         runs-on: windows-latest
         steps:
         - name: step2
           run: echo " hello from job 2"
         - name: Echo today's date
           run: echo "Today's date is $(date +'%Y-%m-%d')"
         - name: setup python
           uses: actions/steup-python@v4
           with:
             python-version: 3.9

    job3:
         runs-on: ubuntu-latest
         steps:
         - name: step 3
           run: echo " hello from job 3"
         - name: Echo today's date
           run: echo "Today's date is $(date +'%Y-%m-%d')"
    
    job4:
         runs-on: ubuntu-latest
         needs: [job1,job2]
         steps:
         - name: step 4
           run: echo " I am job4"
         - name: Echo today's date
           run: echo "Today's date is $(date +'%Y-%m-%d')"
